### PR TITLE
Portfolio: Setup and mobile first

### PR DESCRIPTION
**Pull request by jcmunav63**
NOTE: I crashed my previous repository due to a node_modules error, when trying to fix an error and deleted the node folders; then I couldn't restore it and continue in the same repository (mv_project1), so I started again. Please check my previous pull request at: https://github.com/jcmunav63/mv_project1/pull/1.

**Description**
For the first milestone in the process of creating your portfolio website, you will:

Set up a new repository and prepare it for development using best practices (e.g. linters).
Build the first 2 sections of the mobile website using the template you chose in the previous step.
IMPORTANT NOTE: Read all requirements before you start building your project.

**General requirements**
Make sure that there are [no linter errors](https://github.com/microverseinc/linters-config):
Linter should be set up correctly for this repository.
Linter result should be green.
There should be no custom changes to linter config.
Make sure that you used correct [GitHub Flow](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/github_flow.md):
README file should be descriptive.
Commit messages should be meaningful.
Pull Request should have a descriptive title explaining what changes are inside.
Pull Request should have a short summary describing introduced changes in more detail.
Make sure that you documented your work [in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md):
Branch name should describe a feature or action (e.g. 'created_sidebar' or 'added_comments_section').
Pull Request is made from 'feature branch' into the main branch.
HTML/CSS requirements
Follow our list of [best practices for HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md).
Project requirements
For this project, you should use the [HTML&CSS linter](https://github.com/microverseinc/linters-config/tree/master/html-css)

The 2 sections you need to build for this project are:

- The toolbar (or header).
- The headline section (right after the header).

### CODE REVIEW

**Review by topeogunleye — COMMENTED** [review]
Hi @jcmunav63, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ⚠️

   - You have submitted a project that has failing linters, Kindly make sure your linters are all passing before submitting the PR.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

>Invalid Code Review Request **does not count** into the code reviews limit.

**Review by topeogunleye — APPROVED** [review]
Hi @jcmunav63, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

dwayne-the-rock

## (Highlights) Good Points: 💪 
* Good commit messages. :heavy_check_mark:
* Followed Github flow :heavy_check_mark:
* Professional README file. :heavy_check_mark:
* PR has a good title and summary :heavy_check_mark:

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jcmunav63** [comment]
Thank you very much, Temitope:

I'm grateful for having contacted me. Have a nice day!

Atentamente

Juan Carlos Muñoz Navarrete

**Comment by jcmunav63** [comment]
Merging feature-1 branch (03-25-2023)

**Pull request merged**
